[project]
name = "task-mining-classification"
version = "0.1.0"
description = "Multimodal task mining and classification pipeline for event logs"
authors = [{name = "Your Name", email = "your.email@example.com"}]
requires-python = ">=3.12"
dependencies = [
    "numpy<2",
    "pandas>=2.0.0",
    "scikit-learn>=1.3.0",
    "torch>=2.2.0",
    "pyyaml>=6.0",
    "optuna>=3.5.0",
    ""
]

[project.optional-dependencies]
multimodal = [
    "sentence-transformers",
    "torchvision",
    "Pillow",
]
dev = [
    "jupyter",
    "matplotlib",
    "seaborn",
]

[project.scripts]
train-model = "src.training_pipeline:main"
run-inference = "src.inference:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.hatch.build.targets.sdist]
include = [
    "src/",
    "data/",
    "trained_artifacts/",
    "*.md",
]